appenders:
  file_logger:
    kind: rolling_file
    path: "log/.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)(utc)} - {h({l})}: {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 100mb
      roller:
        kind: delete
root:
  level: info
  appenders:
    - file_logger